"""Ашық/қараңғы Fluent палитра мәндері — ThemeManager QSS-тен бөлек.

``theme_manager.set_theme()`` осы сөздікті модульдегі ``COLOR_*``
атауларына көшіреді. QSS ``build_stylesheet()`` де осы жерден оқиды.
"""

THEME_LIGHT = "light"
THEME_DARK = "dark"

PALETTES: dict[str, dict[str, str]] = {
    THEME_DARK: {
        "COLOR_BACKGROUND": "#1C1C1E",
        "COLOR_SURFACE": "#333336",
        "COLOR_SIDEBAR_BACKGROUND": "#141416",
        "COLOR_SIDEBAR_START": "#101012",
        "COLOR_INPUT": "#3A3A3C",
        "COLOR_GLASS_TOP": "#3A3A42",
        "COLOR_GLASS_BOTTOM": "#26262A",
        "COLOR_BORDER": "#3F3F46",
        "COLOR_BORDER_SUBTLE": "#2A2A2E",
        "COLOR_BORDER_STRONG": "#5A5A62",
        "COLOR_TEXT_PRIMARY": "#F5F5F5",
        "COLOR_TEXT_SECONDARY": "#C8C8C8",
        "COLOR_TEXT_MUTED": "#8D8D8D",
        "COLOR_ACCENT": "#0078D4",
        "COLOR_ACCENT_HOVER": "#1B86D9",
        "COLOR_ACCENT_PRESSED": "#006CBD",
        "COLOR_ACCENT_TEXT": "#FFFFFF",
        "COLOR_ACCENT_GLOW": "#60CDFF",
        "COLOR_SUCCESS": "#0F7B3A",
        "COLOR_WARNING": "#F59E0B",
        "COLOR_ERROR": "#E5534B",
        "COLOR_ERROR_HOVER": "#C13E37",
        "COLOR_INFO": "#4CC2FF",
        "COLOR_HOVER": "#3A3A3C",
        "COLOR_SELECTED": "#0078D4",
        "COLOR_FOCUS_OUTLINE": "#60CDFF",
        "COLOR_ACCENT_SUBTLE": "#1A3A52",
        "COLOR_GRAPH_BACKGROUND": "#2C2C2E",
        "COLOR_GRAPH_GRID": "#3F3F46",
        "COLOR_GRAPH_AXIS": "#F5F5F5",
        "COLOR_GRAPH_TEXT": "#F5F5F5",
        "COLOR_GLASS_BORDER": "rgba(255, 255, 255, 85)",
    },
    THEME_LIGHT: {
        "COLOR_BACKGROUND": "#EEF1F6",
        "COLOR_SURFACE": "#FFFFFF",
        "COLOR_SIDEBAR_BACKGROUND": "#E1E5ED",
        "COLOR_SIDEBAR_START": "#D5DAE3",
        "COLOR_INPUT": "#FFFFFF",
        "COLOR_GLASS_TOP": "#FFFFFF",
        "COLOR_GLASS_BOTTOM": "#F8FAFC",
        "COLOR_BORDER": "#CBD2DC",
        "COLOR_BORDER_SUBTLE": "#EEF0F3",
        "COLOR_BORDER_STRONG": "#9CA6B4",
        "COLOR_TEXT_PRIMARY": "#111827",
        "COLOR_TEXT_SECONDARY": "#6B7280",
        "COLOR_TEXT_MUTED": "#9CA3AF",
        "COLOR_ACCENT": "#2563EB",
        "COLOR_ACCENT_HOVER": "#1D4ED8",
        "COLOR_ACCENT_PRESSED": "#1E40AF",
        "COLOR_ACCENT_TEXT": "#FFFFFF",
        "COLOR_ACCENT_GLOW": "#93C5FD",
        "COLOR_SUCCESS": "#16A34A",
        "COLOR_WARNING": "#F59E0B",
        "COLOR_ERROR": "#DC2626",
        "COLOR_ERROR_HOVER": "#B91C1C",
        "COLOR_INFO": "#0891B2",
        "COLOR_HOVER": "#DCE7FB",
        "COLOR_SELECTED": "#C7DBFA",
        "COLOR_FOCUS_OUTLINE": "#2563EB",
        "COLOR_ACCENT_SUBTLE": "#EFF6FF",
        "COLOR_GRAPH_BACKGROUND": "#FFFFFF",
        "COLOR_GRAPH_GRID": "#CBD2DC",
        "COLOR_GRAPH_AXIS": "#111827",
        "COLOR_GRAPH_TEXT": "#111827",
        "COLOR_GLASS_BORDER": "rgba(15, 23, 42, 55)",
    },
}
